exclude: "node_modules|.git"
default_stages: [pre-commit, pre-push]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "clapgrow_app.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        name: "Run Ruff linter and apply fixes"
        args: ["--fix", "--exit-non-zero-on-fix"]
        language_version: python3.10
      - id: ruff-format
        name: "Format Python code"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write", "--use-tabs", "--tab-width=2", "--print-width=110"]
        types_or: [javascript, vue, scss]
        exclude: |
          (?x)^(
            clapgrow_app/public/dist/.*|
            .*node_modules.*|
            .*boilerplate.*|
            clapgrow_app/templates/includes/.*|
            clapgrow_app/public/js/lib/.*
          )$

  - repo: local
    hooks:
      - id: eslint-fix
        name: "Run ESLint auto-fix before push"
        entry: yarn eslint . --ext .js,.jsx,.ts,.tsx --fix
        language: node
        pass_filenames: false
        stages: [pre-push]
