name: Merge test to main (weekly)

on:
  schedule:
    - cron: '30 14 * * 5' # Friday 8:00 PM IST

jobs:
  merge-test-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Promote test → main
        run: |
          git fetch origin
          CHANGES=$(git log origin/main..origin/test)
          if [ -z "$CHANGES" ]; then
            echo "No new commits from test to main."
            exit 0
          fi

          PR_EXISTS=$(gh pr list --base main --head test --state open --json number --jq '.[0].number')
          if [ -z "$PR_EXISTS" ]; then
            gh pr create --base main --head test --title "Weekly PR: test → main" --body "Promoting test to production"
            PR_EXISTS=$(gh pr list --base main --head test --state open --json number --jq '.[0].number')
          fi

          gh pr merge "$PR_EXISTS" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
